//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        public int usu_id { get; set; }
        public string usu_nombre { get; set; }
        public string usu_apellido { get; set; }
        public string usu_fecha_nac { get; set; }
        public string usu_dni { get; set; }
        public string usu_contraseña { get; set; }
        public string usu_estado { get; set; }
        public string usu_correo { get; set; }
        public string usu_direccion { get; set; }
        public Nullable<int> rol_id { get; set; }
    
        public virtual tbl_rol tbl_rol { get; set; }
    }
}
